//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TocaTudoPlayer.Xamarim.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TocaTudoPlayer.Xamarim.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloaded!.
        /// </summary>
        public static string AlbumDownloadedLabel {
            get {
                return ResourceManager.GetString("AlbumDownloadedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting....
        /// </summary>
        public static string AlbumDownloadInitLabel {
            get {
                return ResourceManager.GetString("AlbumDownloadInitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading.
        /// </summary>
        public static string AlbumDownloadInProgressLabel {
            get {
                return ResourceManager.GetString("AlbumDownloadInProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start download.
        /// </summary>
        public static string AlbumDownloadLabel {
            get {
                return ResourceManager.GetString("AlbumDownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This album is not playable =(.
        /// </summary>
        public static string AlbumIsNotPlayable {
            get {
                return ResourceManager.GetString("AlbumIsNotPlayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album playing!.
        /// </summary>
        public static string AlbumPlayingLabel {
            get {
                return ResourceManager.GetString("AlbumPlayingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline!.
        /// </summary>
        public static string AlbumPlayingOfflineLabel {
            get {
                return ResourceManager.GetString("AlbumPlayingOfflineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllTextLabel {
            get {
                return ResourceManager.GetString("AllTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred =(.
        /// </summary>
        public static string AppDefaultError {
            get {
                return ResourceManager.GetString("AppDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaysEverWish.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ConfigurationLabel {
            get {
                return ResourceManager.GetString("ConfigurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ConfigurationSmallLabel {
            get {
                return ResourceManager.GetString("ConfigurationSmallLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string DeletingLabel {
            get {
                return ResourceManager.GetString("DeletingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including.
        /// </summary>
        public static string InsertingLagel {
            get {
                return ResourceManager.GetString("InsertingLagel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string MusicAlbumButton {
            get {
                return ResourceManager.GetString("MusicAlbumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download music.
        /// </summary>
        public static string MusicCouldNotDownload {
            get {
                return ResourceManager.GetString("MusicCouldNotDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download music please try again =).
        /// </summary>
        public static string MusicCouldNotDownloadTryAgain {
            get {
                return ResourceManager.GetString("MusicCouldNotDownloadTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloaded!.
        /// </summary>
        public static string MusicDownloadedLabel {
            get {
                return ResourceManager.GetString("MusicDownloadedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played.
        /// </summary>
        public static string MusicHistoryRecentlyPlayed {
            get {
                return ResourceManager.GetString("MusicHistoryRecentlyPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This music is not playable =(.
        /// </summary>
        public static string MusicIsNotPlayable {
            get {
                return ResourceManager.GetString("MusicIsNotPlayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to music.
        /// </summary>
        public static string MusicMusicButton {
            get {
                return ResourceManager.GetString("MusicMusicButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved.
        /// </summary>
        public static string MusicSavedButton {
            get {
                return ResourceManager.GetString("MusicSavedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not exists saved musics!.
        /// </summary>
        public static string MusicSavedEmptyRegister {
            get {
                return ResourceManager.GetString("MusicSavedEmptyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MusicSearchButton {
            get {
                return ResourceManager.GetString("MusicSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to play this music =(.
        /// </summary>
        public static string MusicUnableToPlay {
            get {
                return ResourceManager.GetString("MusicUnableToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is on Play Store a new version from the app..
        /// </summary>
        public static string PlayStoreNewVersion {
            get {
                return ResourceManager.GetString("PlayStoreNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please!.
        /// </summary>
        public static string PlayStoreNewVersionAlert {
            get {
                return ResourceManager.GetString("PlayStoreNewVersionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Name.
        /// </summary>
        public static string PopupAlbumNameLabel {
            get {
                return ResourceManager.GetString("PopupAlbumNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Album.
        /// </summary>
        public static string PopupAlbumSelect {
            get {
                return ResourceManager.GetString("PopupAlbumSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert album name is required!.
        /// </summary>
        public static string PopupAlertAlbumNameInsert {
            get {
                return ResourceManager.GetString("PopupAlertAlbumNameInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do delete album ?.
        /// </summary>
        public static string PopupAlertDeleteAlbum {
            get {
                return ResourceManager.GetString("PopupAlertDeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is # music(s) the album &quot;##&quot;, do you wish to remove ?.
        /// </summary>
        public static string PopupDeleteAlbumAlert {
            get {
                return ResourceManager.GetString("PopupDeleteAlbumAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do delete stored music &quot;#&quot; ?.
        /// </summary>
        public static string PopupDeleteMusicAlert {
            get {
                return ResourceManager.GetString("PopupDeleteMusicAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do remove the music &quot;#&quot; from album ?.
        /// </summary>
        public static string PopupDeleteMusicFromAlbum {
            get {
                return ResourceManager.GetString("PopupDeleteMusicFromAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads Loading....
        /// </summary>
        public static string PopupMerchanLoading {
            get {
                return ResourceManager.GetString("PopupMerchanLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PopupMusicDelete {
            get {
                return ResourceManager.GetString("PopupMusicDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PopupMusicEdit {
            get {
                return ResourceManager.GetString("PopupMusicEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PopupMusicSave {
            get {
                return ResourceManager.GetString("PopupMusicSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string PopupMusicSaved {
            get {
                return ResourceManager.GetString("PopupMusicSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved in Album! - .
        /// </summary>
        public static string PopupMusicSavedInAlbum {
            get {
                return ResourceManager.GetString("PopupMusicSavedInAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string PopupMusicStart {
            get {
                return ResourceManager.GetString("PopupMusicStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not be played =(.
        /// </summary>
        public static string StartForegroundServiceDefaultExceptionMsg {
            get {
                return ResourceManager.GetString("StartForegroundServiceDefaultExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again!.
        /// </summary>
        public static string TryAgainLabel {
            get {
                return ResourceManager.GetString("TryAgainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string UpdatingLagel {
            get {
                return ResourceManager.GetString("UpdatingLagel", resourceCulture);
            }
        }
    }
}
