//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TocaTudoPlayer.Xamarim.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TocaTudoPlayer.Xamarim.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloaded!.
        /// </summary>
        public static string AlbumDownloadedLabel {
            get {
                return ResourceManager.GetString("AlbumDownloadedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting....
        /// </summary>
        public static string AlbumDownloadInitLabel {
            get {
                return ResourceManager.GetString("AlbumDownloadInitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading.
        /// </summary>
        public static string AlbumDownloadInProgressLabel {
            get {
                return ResourceManager.GetString("AlbumDownloadInProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start download.
        /// </summary>
        public static string AlbumDownloadLabel {
            get {
                return ResourceManager.GetString("AlbumDownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This album is not playable =(.
        /// </summary>
        public static string AlbumIsNotPlayable {
            get {
                return ResourceManager.GetString("AlbumIsNotPlayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline!.
        /// </summary>
        public static string AlbumPlayingOfflineLabel {
            get {
                return ResourceManager.GetString("AlbumPlayingOfflineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayEverWish.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.
        /// </summary>
        public static string MusicAlbumButton {
            get {
                return ResourceManager.GetString("MusicAlbumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloaded!.
        /// </summary>
        public static string MusicDownloadedLabel {
            get {
                return ResourceManager.GetString("MusicDownloadedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This music is not playable =(.
        /// </summary>
        public static string MusicIsNotPlayable {
            get {
                return ResourceManager.GetString("MusicIsNotPlayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to music.
        /// </summary>
        public static string MusicMusicButton {
            get {
                return ResourceManager.GetString("MusicMusicButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved.
        /// </summary>
        public static string MusicSavedButton {
            get {
                return ResourceManager.GetString("MusicSavedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MusicSearchButton {
            get {
                return ResourceManager.GetString("MusicSearchButton", resourceCulture);
            }
        }
    }
}
